[Interface]
PrivateKey = YKWMb5irMeY1cQxw02q9Leth5nnUyAtXc6Q0m0dp+G4=
Address = 10.66.66.2/32,fd42:42:42::2/128
DNS = 1.1.1.1,1.0.0.1

# Uncomment the next line to set a custom MTU
# This might impact performance, so use it only if you know what you are doing
# See https://github.com/nitred/nr-wg-mtu-finder to find your optimal MTU
# MTU = 1420

[Peer]
PublicKey = uThFQvvwgMt9WjCD49NgRpFQO1AVIFrHoP+gHyrt1is=
PresharedKey = f5WGM/+l8WqPlOgqurq6z3CnDAvAPdKqKmtwozxc68E=
Endpoint = 201.24.48.108:63384
AllowedIPs = 0.0.0.0/0,::/0
